Cray-HPE/hms-smd-charts

changelog/v2.0.md
charts/v2.0/cray-hms-smd/Chart.yaml
charts/v2.0/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

This change updates the HMS CT smoke tests to execute the HSM tests first to more easily and clearly identify discovery-related problems.
* Resolves CASMHMS-5205
This change was tested by deploying the updated smoke tests and wrapper script to Wasp, executing them, and verifying that the HSM tests ran first. Failures of the HSM smoke tests were also verified to stop execution of the wrapper script as expected.
Was a fresh Install tested? Y
Was an Upgrade tested? N
Was a Downgrade tested? N
Low risk.

CASMHMS-5205 Reorder HMS CT smoke test execution

---

changelog/v2.0.md
charts/v2.0/cray-hms-smd/Chart.yaml
charts/v2.0/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

This change adds support for HPE PDUs to the ComponentEndpoints CT test.
* Resolves CASMTRIAGE-2801.
This change was tested by deploying the updated HSM ComponentEndpoints CT test to the system Hela which has HPE PDUs, executing the test, and verifying that the previously failing test cases began to pass.
Was a fresh Install tested? Y
Was an Upgrade tested? N
Was a Downgrade tested? N
Low-risk change that impacts HSM CT testing only.

CASMTRIAGE-2801 Add support for HPE PDUs to ComponentEndpoints CT test.

---

changelog/v2.0.md
charts/v2.0/cray-hms-smd/Chart.yaml
charts/v2.0/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

HSM now uses latest hms-msgbus, which replaces buggy the Sarama kafka
GO library with the more mature and stable Confluent.
Resolves, in part, CASMHMS-3090.

HSM now uses latest hms-msgbus.

---

changelog/v2.0.md
charts/v2.0/cray-hms-smd/Chart.yaml
charts/v2.0/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

This change adds the following HSM Redfish endpoint unit tests:
- TestDoRedfishEndpointGet(), 4 test cases
- TestDoRedfishEndpointQueryGet(), 5 test cases
- TestDoRedfishEndpointDelete(), 5 test cases
- TestDoRedfishEndpointsDeleteAll(), 5 test cases
- TestDoRedfishEndpointPut(), 4 test cases
- TestDoRedfishEndpointsPost(), 4 test cases
* Resolves CASMHMS-634.
This change was tested by executing the new HSM unit tests locally as well as in the Jenkins build pipeline and verifying that they passed.
Was a fresh Install tested? N
Was an Upgrade tested? N
Was a Downgrade tested? N
Low risk.

CASMHMS-634 Add HSM Redfish endpoint unit tests

---

changelog/v2.0.md
charts/v2.0/cray-hms-smd/Chart.yaml
charts/v2.0/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

This change adds support for the 'GET' operation to the HSM /v2/locks/status API which will list the lock status of all components in HSM. Optional query parameters may be supplied to filter the results based on component Type, State, Role, SubRole, and Locked, Reserved, ReservationDisabled status. Several corrections to the HSM Swagger specification and a few minor CT test updates are also included.
* Resolves CASMHMS-4974.
This change was tested by:
- Implementing unit tests for the new /v2/locks/status 'GET' operation
- Spinning up a local instance of HSM in a docker-compose environment, manually populating it with components and setting locks, and executing calls with various query parameters specified
- Upgrading the running HSM service on Mug using Helm to deploy the new version and …

CASMHMS-4974 Add support for HSM /v2/locks/status 'GET' operation for listing all locks

---

changelog/v2.0.md
charts/v2.0/cray-hms-smd/Chart.yaml
charts/v2.0/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

Update to hms-smd version 1.50.0 for fixing an issue causing FRU data to get improperly populated for empty locations.
* Resolves [CASMHMS-5511](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5511)
For testing, see https://github.com/Cray-HPE/hms-smd/pull/74
none

Update to hms-smd version 1.50.0

---

changelog/v2.0.md
changelog/v2.1.md
charts/v2.0/cray-hms-smd/Chart.yaml
charts/v2.0/cray-hms-smd/values.yaml
charts/v2.1/cray-hms-smd/Chart.yaml
charts/v2.1/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

Updates the HSM image version for CASMTRIAGE-3430
ChassisBMC discovery is complete, it should check that all child components are correctly marked as Mountain components. The filtering for identifying the child components was incorrect. This mod fixes the issue.
This also changes HSM to get class from SLS for node components.
* Resolves [CASMTRIAGE-3430](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3430)
For testing see https://github.com/Cray-HPE/hms-smd/pull/76
Low

Change HSM to get node class from SLS

---

LICENSE
changelog/v2.1.md
charts/v2.1/cray-hms-smd/Chart.yaml
charts/v2.1/cray-hms-smd/templates/tests/test-functional.yaml
charts/v2.1/cray-hms-smd/templates/tests/test-smoke.yaml
cray-hms-smd.compatibility.yaml

This PR includes the following changes:
- Set CT test job backoffLimit to zero so retries aren't attempted on failures
- Set holdApplicationUntilProxyStarts pod annotation for istio sidecar to cleanup the "Waiting for Sidecar" code
* Partially resolves CASMHMS-5575.
See testing from: https://github.com/Cray-HPE/hms-bss-charts/pull/15
Low risk, minor changes to new Helm CT test job configuration

CASMHMS-5575 Helm CT Test job configuration updates for no retries and istio sidecar

---

changelog/v2.1.md
charts/v2.1/cray-hms-smd/Chart.yaml
charts/v2.1/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

This updates the HSM image version to pick up changes to HSM to ignore switch and baseboard components that are marked as type=GPU when discovering GPUs in proliant iLO devices.
* Resolves [CASMHMS-4972](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-4972)
* Resolves [CASMHMS-4973](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-4973)
For testing, see https://github.com/Cray-HPE/hms-smd/pull/77
Low

Update HSM image version for CASMHMS-4972 and CASMHMS-4973

---

changelog/v2.1.md
charts/v2.1/cray-hms-smd/Chart.yaml
charts/v2.1/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

Improve HSM's postgres schema for FRU history pruning.
* Resolves [CASMHMS-5591](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5591)
For testing, see https://github.com/Cray-HPE/hms-smd/pull/78
None

Add indexes for hwinv_hist to speed up history event pruning

---

changelog/v2.1.md
charts/v2.1/cray-hms-smd/Chart.yaml
charts/v2.1/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

This PR includes the following changes:
- Update CT tests to stable hms-test:3.1.0 image (upgrades pytest and tavern to work around python issue43798)
- Pull Alpine base image from correct location in algol60 artifactory
- CT test cleanup
* Partially resolves CASMHMS-5458.
This change was tested by deploying the updated version of the service and chart onto Mug, executing the Helm CT tests, and verifying that they passed.
Was a fresh Install tested? N
Was an Upgrade tested? Y
Was a Downgrade tested? N
Low risk, test update.

CASMHMS-5458 Coordination for HMS CT Helm tests

---

changelog/v3.0.md
charts/v3.0/cray-hms-smd/Chart.yaml
charts/v3.0/cray-hms-smd/templates/jobs.yaml
charts/v3.0/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

CASMHMS-5610 - Fixed POST /Inventory/RedfishEndpoints returning 500 instead of 409 for conflicts.
CASMHMS-5463 - smd-init job permissions issues
* Resolves [CASMHMS-5610](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5610)
* Resolves [CASMHMS-5463](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5463)
For testing see https://github.com/Cray-HPE/hms-smd/pull/81

Fix POST /Inventory/RedfishEndpoints returning 500 instead of 409 for conflicts

---

changelog/v4.0.md
charts/v4.0/cray-hms-smd/Chart.yaml
charts/v4.0/cray-hms-smd/templates/tests/test-functional.yaml
charts/v4.0/cray-hms-smd/templates/tests/test-smoke.yaml
charts/v4.0/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

This change updates the HSM CT tests to use the latest hms-test:4.0.0 image and RIE for HMTH.
* Resolves CASMHMS-5858.
This change was tested by deploying the updated HSM Helm chart on Mug, running the CT tests, and verifying that they passed.
Was a fresh Install tested? N
Was an Upgrade tested? Y
Was a Downgrade tested? Y
Low risk, pulls in new testing infrastructure for HMTH.

CASMHMS-5858 HSM to v1.61.0 for HMTH changes

---

changelog/v4.0.md
charts/v4.0/cray-hms-smd/Chart.yaml
charts/v4.0/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

Update the HSM chart to 1.62.0 for CASMTRIAGE-4744 to fix HSN NIC discovery.
* Resolves [CASMTRIAGE-4744](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4744)
For testing, see https://github.com/Cray-HPE/hms-smd/pull/94
Low

Fix HSN NIC discovery

---

changelog/v5.0.md
charts/v5.0/cray-hms-smd/.gitignore
charts/v5.0/cray-hms-smd/Chart.yaml
charts/v5.0/cray-hms-smd/templates/NOTES.txt
charts/v5.0/cray-hms-smd/templates/_helpers.tpl
charts/v5.0/cray-hms-smd/templates/configmap.yaml
charts/v5.0/cray-hms-smd/templates/destinationrules.yaml
charts/v5.0/cray-hms-smd/templates/hook-serviceaccount.yaml
charts/v5.0/cray-hms-smd/templates/jobs.yaml
charts/v5.0/cray-hms-smd/templates/pvc.yaml
charts/v5.0/cray-hms-smd/templates/tests/test-functional.yaml
charts/v5.0/cray-hms-smd/templates/tests/test-smoke.yaml
charts/v5.0/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

This creates the v5.0 chart for HSM with v1 APIs removed.
* Resolves [CASMHMS-5626](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5626)
For testing, see https://github.com/Cray-HPE/hms-smd/pull/96
Low

Remove HSM v1 APIs

---

changelog/v6.0.md
charts/v6.0/cray-hms-smd/.gitignore
charts/v6.0/cray-hms-smd/Chart.yaml
charts/v6.0/cray-hms-smd/templates/NOTES.txt
charts/v6.0/cray-hms-smd/templates/_helpers.tpl
charts/v6.0/cray-hms-smd/templates/configmap.yaml
charts/v6.0/cray-hms-smd/templates/destinationrules.yaml
charts/v6.0/cray-hms-smd/templates/hook-serviceaccount.yaml
charts/v6.0/cray-hms-smd/templates/jobs.yaml
charts/v6.0/cray-hms-smd/templates/pvc.yaml
charts/v6.0/cray-hms-smd/templates/tests/test-functional.yaml
charts/v6.0/cray-hms-smd/templates/tests/test-smoke.yaml
charts/v6.0/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

Fixed deprecated k8s API's by updating to 9.0.0, with the exception that cert-manager.io can't be updated now until the implementation of this API is updated. When this is possible the change will need to be made in the cray-service chart. The cert-manager.io API is deprecated but not removed, so changing it is not urgent.
Here is the diff between version v5.0 and v6.0
```
shunr@fedora> diff -r charts/v5.0/ charts/v6.0/
diff -r charts/v5.0/cray-hms-smd/Chart.yaml charts/v6.0/cray-hms-smd/Chart.yaml
3c3
< version: 5.0.0
---
> version: 6.0.0
10c10
<     version: "~8.2.3"
---
>     version: "~9.0.0"
```
The branch `fix-k8s-deprecation-casmhms-5881-test` contains these changes and changes for a workflow that detects k8s api deprecations.
- Here are results before the fix: …

Updated API versions for k8s deprecated APIs

---

LICENSE
changelog/v5.0.md
changelog/v6.0.md
charts/v5.0/cray-hms-smd/Chart.yaml
charts/v5.0/cray-hms-smd/templates/tests/check-hardware.yaml
charts/v5.0/cray-hms-smd/values.yaml
charts/v6.0/cray-hms-smd/Chart.yaml
charts/v6.0/cray-hms-smd/templates/tests/check-hardware.yaml
charts/v6.0/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

This change moves the HMS CT tests that run in the CSM validation steps and often fail due to hardware issues into a new hardware-checks test stage that is separate from the rest of the HMS tests. These tests are optional and do not block CSM installs or upgrades.
* Resolves CASMHMS-5640
This change was tested in the build pipeline, as well as on Surtur by deploying the updated tests and wrapper scripts, executing various sets of tests and hardware checks, and verifying that they all passed. Testing was also completed to verify that both test and hardware-check failures were handled properly.
Low risk, impacts HMS CT testing only.

CASMHMS-5640 Move hardware-sensitive HMS CT tests into separate stage

---

changelog/v6.0.md
charts/v6.0/cray-hms-smd/Chart.yaml
charts/v6.0/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

This change includes many additions, updates, and fixes to the HSM CT tests:
* Finish test cases for HSM groups/add test cases for exclusive groups.
* Update hardware tests to no longer fail on unpopulated modules.
* Finish test cases for HSM ComponentEndpoints.
* Fix bug that caused certain validation functions to be silently skipped.
* Add tests for the DiscoveryStatus API.
* Add tests for the Discover API.
* Finish test cases for HSM partitions.
* Add tests for the memberships API.
* Add tests for the State Change Notifications API.
* Resolves CASMHMS-5647.
* Resolves CASMHMS-5708.
* Resolves CASMHMS-5883.
* Resolves CASMHMS-5705.
* Partially resolves CASMHMS-5924.
* Resolves CASMHMS-5711.
* Resolves CASMHMS-5712.
* Resolves CASMHMS-5709.
* Resolves CASMHMS-5710.
* Resolves …

CASMHMS-5747 Finish HSM CT Test Work for HMTH

---

.github/workflows/k8s_api_checker.yaml

Added the workflow to check for deprecated k8s APIs
The workflow is currently configured to report deprecated APIs, but not to fail,
since the deprecated APIs in this project have not been fixed. These APIs will
be fixed when kubernetes and cert manager are updated in CSM.
* Resolves [CASMHMS-5842](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5842)
Tested on:
* various projects with various PRs and branches

Kubernetes api checker casmhms 5842

---

changelog/v7.0.md
charts/v7.0/cray-hms-smd/Chart.yaml
charts/v7.0/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

This updates the HSM image version for CASMHMS-5951 - Add RTS management switch discovery to HSM.
* Resolves [CASMHMS-5951](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5951)
For testing, see https://github.com/Cray-HPE/hms-smd/pull/112
low

Add RTS management switch discovery to HSM

---

changelog/v7.0.md
charts/v7.0/cray-hms-smd/Chart.yaml
charts/v7.0/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

This fixes node architecture discovery in HSM so that ARM nodes will have the correct ARCH field under `/State/Components`.
* Resolves [CASMHMS-5958](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5958)
For testing, see https://github.com/Cray-HPE/hms-smd/pull/114
low

Fix node architecture discovery

---

.github/workflows/k8s_api_checker.yaml
changelog/v7.0.md
charts/v7.0/cray-hms-smd/Chart.yaml
cray-hms-smd.compatibility.yaml

For the k8s 1.22 upgrade, this PR makes the following changes
* rebuilds to pick up base-charts:  cray-service 10.0.2, and cray-postgresql 1.0.1
* It documents which version is for k8s 1.22 or later
* Configures the deprecated k8s api checker to fail when there are deprecated APIs
* Resolves [CASMHMS-5881](https://jira-pro.it.hpe.com:8443/browse/CASMHMS-5881)
Tested on:
* No additional testing beyond the automated tests
Were the install/upgrade based validation checks/tests run?(goss tests/install-validation doc)
Were continuous integration tests run? Y/N   If not, Why? N
Was an Upgrade tested?                 Y/N   If not, Why? N
Was a Downgrade tested?                Y/N   If not, Why? N

Updated cray-service version to 10.0.2 for k8s 1.22

---

changelog/v7.0.md
charts/v7.0/cray-hms-smd/Chart.yaml
charts/v7.0/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

Fixes a bug in HSN NIC numbering that is causing discovery errors when 4 HSN NICs are present in CSM 1.5 and 1.6.
* Resolves [CASMTRIAGE-5914](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5914)
For testing see https://github.com/Cray-HPE/hms-smd/pull/118
None

Fix HSN NIC numbering

---

changelog/v7.1.md
charts/v7.1/cray-hms-smd/Chart.yaml
charts/v7.1/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

HSM's FRU tracking was not creating a new 'Detected' event after a 'Removed' event if the same FRU was detected (Removed and put back in the same spot).
* Resolves [CASMHMS-6096](https://jira-pro.it.hpe.com:8443/browse/CASMHMS-6096)
For testing see https://github.com/Cray-HPE/hms-smd/pull/122
Low

Change FRU history to create 'Detected' events after 'Removed' events

---

changelog/v7.1.md
charts/v7.1/cray-hms-smd/Chart.yaml
charts/v7.1/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

Paradise hardware lacks the standard /redfish/v1/Systems/system/EthernetInterfaces redfish endpoint for network interfaces attached to the in-band node.  Instead, they've provided multiple locations that must be scanned underneath the /redfish/v1/Systems/system/Oem/Insyde/Ncsi endpoint.  This PR includes a new redfish-foxconn.go file with all the associated data structures and code necessary to parse through this tree for all of the network interfaces attached to the host node.
A sample output of 'cray hsm inventory' is as follows:
> ncn-m001:~ # cray hsm inventory componentEndpoints describe x3000c0s33b4n0 --format json | jq .RedfishSystemInfo.EthernetNICInfo
[
{
"RedfishId": "ncsi1-p1-c0-primary_eth",
"@odata.id": "/redfish/v1/Systems/system/Oem/Insyde/Ncsi/1/Package/1",
"Description": …

CASMHMS-6163: Discover Paradise node MACs using correct redfish endpoint

---

changelog/v7.0.md
changelog/v7.1.md
charts/v7.0/cray-hms-smd/Chart.yaml
charts/v7.0/cray-hms-smd/values.yaml
charts/v7.1/cray-hms-smd/Chart.yaml
charts/v7.1/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

There are a number of discovery changes in this PR related to Foxconn Paradise discovery.
The Paradise redfish Power endpoint presents the consumed watts value as a float. All prior platforms have presented it as an integer value and thus the smd data structure for holding it declared it as an int. This caused json.Unmarshal() to fail on Paradise because it enforces strict type checking.  The fix here is to change the int type to an interface{} type so that it can hold a value of any type. We then convert any floats we read to an int (by rounding). We chose to do this rather than simply changing the type from an int to a float so that we don't break any customer code that may be doing the same thing we were doing (expecting an int rather than a float).
During chassis discovery, we now …

Casmhms 6148.final

---

changelog/v7.0.md
changelog/v7.1.md
charts/v7.0/cray-hms-smd/Chart.yaml
charts/v7.0/cray-hms-smd/values.yaml
charts/v7.1/cray-hms-smd/Chart.yaml
charts/v7.1/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

Updated regex patterns in the tavern tests to handle the new Foxconn Paradise ethernet interface names.  Without these changes, the SMD functional tests were failing on systems with Foxconn Paradise hardware.
Adopted app version 2.11.9 for CSM 1.5.2 (helm chart 7.0.13)
Adopted app version 2.20.0 for CSM 1.6 (helm chart 7.1.8)
* Resolves [CASMHMS-6201](https://jira-pro.it.hpe.com:8443/browse/CASMHMS-6201)
Tested on:
* tyr
Aftur upgrading SMD with changes, verified smoke and functional tests passed when running:
`/opt/cray/csm/scripts/hms_verification/run_hms_ct_tests.sh -t hsm`
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? Y
- Were continuous integration tests run? If not, why? :
- Was upgrade tested? If not, why? Y
- …

CASMHMS-6201: Updated tavern tests to handle Foxconn Paradise ethernet interface names

---

changelog/v7.0.md
changelog/v7.1.md
charts/v7.0/cray-hms-smd/Chart.yaml
charts/v7.0/cray-hms-smd/values.yaml
charts/v7.1/cray-hms-smd/Chart.yaml
charts/v7.1/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

I neglected to run the functional tests when pushing up my last CASMHMS-6199 changes.  After pushing them up, I ran the functional tests and found that they failed because of the new Paradise chassis type 'Zone'.  This change updates the test so that type 'Zone' is recognized, and will not fail the test.
Adopted app version 2.11.11 for CSM 1.5.2 (helm chart 7.0.15)
Adopted app version 2.22.0 for CSM 1.6 (helm chart 7.1.10)
* Resolves: CASMHMS-6199
Tested on:
* tyr
Ran '/opt/cray/csm/scripts/hms_verification/run_hms_ct_tests.sh -t hsm' and verified the tests ran successfully.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? Y
- Were continuous integration tests run? If not, why? Y
- Was upgrade tested? If not, why? Y
- Was …

CASMHMS-6199: Add 'Zone' chassis type to tavern test

---

.github/workflows/build_and_release_charts.yaml
changelog/v7.0.md
changelog/v7.1.md
charts/v7.0/cray-hms-smd/Chart.yaml
charts/v7.0/cray-hms-smd/values.yaml
charts/v7.1/cray-hms-smd/Chart.yaml
charts/v7.1/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

This is to pull in these fixes:
CSM 1.5.2: https://github.com/Cray-HPE/hms-smd/pull/148
CSM 1.6.0: https://github.com/Cray-HPE/hms-smd/pull/149
The main code change PR is the one for CSM 1.4.5, but for that version we're not making a new chart, just a new image:
https://github.com/Cray-HPE/hms-smd/pull/147

CASMHMS-5838: Fix bugs that break bulk component role/subrole updates

---

changelog/v7.0.md
changelog/v7.1.md
charts/v7.0/cray-hms-smd/Chart.yaml
charts/v7.0/cray-hms-smd/values.yaml
charts/v7.1/cray-hms-smd/Chart.yaml
charts/v7.1/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

Hardare tavern test was failing when run against Paradise.  Paradise includes a new processor type "FPGA" that was not expected by the test.  The change here is to add "FPGA" as a valid processor type.  This was not hit previously because the tavern tests do not test against each node type on a system.  Node selection is random, and we got unlucky that no Paradise node had been previously chosen.
Adopted app version 2.11.15 for CSM 1.5.2 (helm chart 7.0.19)
Adopted app version 2.26.0 for CSM 1.6 (helm chart 7.1.14)
* Resolves [CASMTRIAGE-7079](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-7079)
* Change will also be needed in `master` (ie. 1.6)
Tested on:
* `tyr`
Made a temporary change to the test_hardware.tavern.yaml file:
` -      url: …

CASMTRIAGE-7079: Paradise: Fixed functional hardware test to pass processor types of "FPGA"

---

changelog/v7.0.md
changelog/v7.1.md
charts/v7.0/cray-hms-smd/Chart.yaml
charts/v7.0/cray-hms-smd/values.yaml
charts/v7.1/cray-hms-smd/Chart.yaml
charts/v7.1/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

In BMC fw 1.17, Foxconn changed the behavior associated with reading the /Power endpoint in the ProcessorModule_0 chassis over redfish.  In previous versions, the read just failed and returned no data when the data was not yet available (ie. when node power was off, or shortly after when node power was turned on).  SMD was coded to retry until the read succeeded, up to four times.  When it did finally succeed, the data returned was always correct as BMC fw did not allow it to be read until the data was available.  With BMC fw v1.17, the /Power endpoint no longer returns an error when the data is not available (again, when node power is off or shortly after it is turned on).  If the data is not yet available on the BMC,  the BMC fw simply returns zero or nil for it.  This means that the …

CASMHMS-6233: Paradise: Adapted SMD to BMC fw changing the behavior of the /Power endpoint read over redfish

---

changelog/v7.1.md
charts/v7.1/cray-hms-smd/Chart.yaml
charts/v7.1/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

In CSM 1.6 Kubernetes is being updated to 1.24
- Updated the cray-service chart to 11.0.0
- Updated docker-kubectl to 1.24.17
Adopted helm chart 7.1.17 for this.  There was no change in app version.
* Resolves [CASMHMS-6261](https://jira-pro.it.hpe.com:8443/browse/CASMHMS-6261)
Tested on:
* `fanta` (running Kubernetes v1.24.17)
All testing was done with the new cray-service 10.0.6.  After testing completed, was asked to use 11.0.0 instead of 10.0.6 but was informed that no testing of 11.0.0 was required to be done if already tested with 10.0.6 because it is the exact same, just a different version number.
- Upgraded to new chart with 'helm upgrade'
- Because pods don't restart after upgrade if there was no container change, manually restarted them with 'kubectl rollout …

CASMHMS-6261: Updated dependences for Kubernetes 1.24

---

changelog/v7.1.md
charts/v7.1/cray-hms-smd/Chart.yaml
charts/v7.1/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

Added support for building a pprof enabled image.  Profiling adds runtime overhead so the pprof enabled image is not used by default.  It is meant to be a debug tool.  In order to use the enabled pprof image, edit the deployment and append "-pprof" to the image name.  For unstable developer builds, be sure to change the built timestamp as well.
Adopted app version 2.31.0 for CSM 1.6.1 (helm chart 7.1.20)
* Resolves [CASMHMS-6324](https://jira-pro.it.hpe.com:8443/browse/CASMHMS-6324)
Tested on:
* `mug`
- Deployed service with pprof enabled - confirmed pprof functionality
- Deployed services with pprof disabled - confirmed pprof support not built into binary
- Functional tests (if they exist) was successfully ran with and without pprof enabled
Test Checklist:
- Were the …

CASMHMS-6324: Added support for ppprof builds

---

changelog/v7.2.md
charts/v7.2/cray-hms-smd/.gitignore
charts/v7.2/cray-hms-smd/Chart.yaml
charts/v7.2/cray-hms-smd/templates/NOTES.txt
charts/v7.2/cray-hms-smd/templates/_helpers.tpl
charts/v7.2/cray-hms-smd/templates/configmap.yaml
charts/v7.2/cray-hms-smd/templates/destinationrules.yaml
charts/v7.2/cray-hms-smd/templates/hook-serviceaccount.yaml
charts/v7.2/cray-hms-smd/templates/jobs.yaml
charts/v7.2/cray-hms-smd/templates/pvc.yaml
charts/v7.2/cray-hms-smd/templates/tests/check-hardware.yaml
charts/v7.2/cray-hms-smd/templates/tests/test-functional.yaml
charts/v7.2/cray-hms-smd/templates/tests/test-smoke.yaml
charts/v7.2/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

Updated image and module dependencies for security updates.
Fixed a bunch of pre-existing build warnings in Dockerfiles as it was difficult to look for possible new warnings/errors associated with the image and module updates.
Added image-pprof Makefile support as the above module updates fixed the back-end ARM build issue associated with not being able to enable it previously.
The tavern tests were updated to look for a returned 404 http code rather than a 405 code due to the gorilla/mux change https://github.com/gorilla/mux/pull/712 that came with updating the gorilla module.
Updates to hms-certs, hms-compcredentials, and hms-securestorage were not included.  A new Jira will be created to handle them seperately.  This is because updating these modules will require functional changes …

CASMHMS-5678: Update image and module dependencies

---

changelog/v7.2.md
charts/v7.2/cray-hms-smd/Chart.yaml
charts/v7.2/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

Updated module dependencies for security updates.
The hms-certs update required changes to pass vault related override values to hms-certs.
Adopted app version 2.34.0 for CSM 1.7.0 (helm chart 7.2.1)
* Resolves [CASMHMS-5678](https://jira-pro.it.hpe.com:8443/browse/CASMHMS-5678)
Ran smoke and integration tests.
Tested on:
* `mug`
Were the install/upgrade based validation checks/tests run?(goss tests/install-validation doc) Y
Were continuous integration tests run? Y/N   If not, Why? Y
Was an Upgrade tested?                 Y/N   If not, Why? Y 
Was a Downgrade tested?                Y/N   If not, Why? Y

CASMHMS-5678: Update module dependencies related to vault and hms-certs

---

changelog/v7.2.md
charts/v7.2/cray-hms-smd/Chart.yaml
charts/v7.2/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

Updated all module and image dependencies to latest versions.  The primary reason for this was to pick up some resource leak fixes to the hms-base, hms-certs, and hms-go-http-lib modules.  Several sections of SMD code were removed and/or replaced due to the most recent changes to hms-base.
Additionally upgraded Go from v1.23 to v1.24.  There were a number of SMD code changes that were required to support differences in these two version of Go.
Adopted app version 2.37.0 for CSM 1.7.0 (helm chart 7.2.4).
* Resolves [CASMHMS-6482](https://jira-pro.it.hpe.com:8443/browse/CASMHMS-6482)
Tested on:
* `mug`
Upgraded to dev version of SMD.  Watched log files to ensure nothing obvious was wrong.  Ran the standard SMD smoke and functional tests which all passed.  Ran xtdiscover …

CASMHMS-6482: Update modules to pull in fixes to resource issues in HMS modules

---

changelog/v7.2.md
charts/v7.2/cray-hms-smd/Chart.yaml
charts/v7.2/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

Added 'curl' command to container image and removed all future potential for false positive failures in the CT tests associated with ethernet device naming.
Adopted app version 2.38.0 for CSM 1.7.0 (helm chart 7.2.5).
* Resolves [CASMHMS-6499](https://jira-pro.it.hpe.com:8443/browse/CASMHMS-6499)
* Resolves [CASMTRIAGE-8079](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-8079)
Tested on:
* Local development environment
* mug
Loaded image into Docker Desktop on laptop and verified 'curl' command was present.  No further testing necessary.
Loaded onto mug and ran CT tests to verify tests still pass.

CASMHMS-6499: Added 'curl' command to container image and fix CT test

---

changelog/v7.2.md
charts/v7.2/cray-hms-smd/Chart.yaml
cray-hms-smd.compatibility.yaml

Updated cray-postgresql and cray-service dependencies to the latest versions
New helm chart version is 7.2.6 (no app version change)
* Resolves [CASMHMS-6516](https://jira-pro.it.hpe.com:8443/browse/CASMHMS-6516)
Tested on:
* `beau` (vshasta)
- Helm upgrade of the new chart
- Had to do a 'rollout restart' to restart the pods since the container image didn't change
- Ran HMS CT tests
- Verified wait-for-postgres pod ran and functioned correctly
- Helm rollback to the prior version of the service

CASMHMS-6516: Bump postgresql and cray-service to latest versions

---

changelog/v7.2.md
charts/v7.2/cray-hms-smd/Chart.yaml
charts/v7.2/cray-hms-smd/values.yaml
cray-hms-smd.compatibility.yaml

Updated Alpine base image from 3.21 to 3.22 to pick up security fixes.
Updated CT test image version dependencies so that the test infractructure is always references the latest versions of HMS services.
Also updated the Go module dependencies for HMS libraries and services.
Adopted app version 2.43.0 for CSM 1.7.1 (helm chart 7.2.11)
* Resolves [CASMHMS-6551](https://jira-pro.it.hpe.com:8443/browse/CASMHMS-6551)
Tested via pipeline execution of CT tests and on system mug.

CASMHMS-6551: Update misc SMD dependencies for CSM 1.7.1
